### ISSUE TITLE
deepin15.10.1下面安装了qt5-default后编译不过

### ISSUE THREAD

**Issue by widon1104** [xyz1001/dde-system-monitor#1]
widon@widon-PC:~/soft/dde-plugin/dde-system-monitor$ make
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o monitorplugin.o src/monitorplugin.cpp
src/monitorplugin.cpp: In member function ‘virtual bool SystemMonitorPlugin::eventFilter(QObject*, QEvent*)’:
src/monitorplugin.cpp:169:27: **error: ‘class PluginProxyInterface’ has no member named ‘requestContextMenu’**
             m_proxyInter->requestContextMenu(this, key);
                           ^~~~~~~~~~~~~~~~~~
src/monitorplugin.cpp: In member function ‘virtual QWidget* SystemMonitorPlugin::itemWidget(const QString&)’:
src/monitorplugin.cpp:36:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:367: recipe for target 'monitorplugin.o' failed
make: *** [monitorplugin.o] Error 1

**Comment by xyz1001** [comment]
dde接口又改了，已修复

**Comment by widon1104** [comment]
这个插件安装上去是什么效果，能不能截个图放在介绍里面啊
